# Generated by Django 3.2 on 2024-09-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_auto_20240905_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='storyline',
            field=models.CharField(max_length=300),
        ),
    ]
